### ISSUE TITLE
Trying to run have this problem

### ISSUE THREAD

**Issue by sinfocomp** [timkrins/pretendcnc#1]
Traceback (most recent call last):
  File "D:\Downloads\pretendcnc-master\pretendcnc.py", line 77, in <module>
    ser = SerialSetup()
  File "D:\Downloads\pretendcnc-master\pretendcnc.py", line 29, in SerialSetup
    ser = serial.Serial('COM7',115200,8,'N',1,0.01)
AttributeError: module 'serial' has no attribute 'Serial'

**Comment by timkrins** [comment]
hi there. i wrote this so long ago that I don't even remember what I wrote it for.
it probably doesn't do what you want it to do.
